---

- name: Prepare webservers
  hosts: all
  remote_user: root
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: python3-pip
        update_cache: yes

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

- name: Install datadog
  hosts: webservers
  remote_user: root

  tasks:
    - name: Setup datadog
      include_role:
        name: datadog.datadog

- name: Deploy application
  hosts: all
  remote_user: root
  tags: deploy

  tasks:
    - name: Setup environment variables
      template:
        src: templates/environment.j2
        dest: .env

    - name: Run container
      community.docker.docker_container:
        name: redmine
        image: redmine:latest
        published_ports:
          - "{{ app_port }}:3000"
        restart_policy: always
        restart: yes
        container_default_behavior: no_defaults
        pull: yes
        env_file: .env
