---

- name: Prepare webservers
  hosts: all
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: python3-pip
        update_cache: yes

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

- name: Deploy application
  hosts: all
  tags: deploy

  tasks:
    - name: Setup environment variables
      template:
        src: templates/environment.j2
        dest: .env

    - name: Run container
      community.docker.docker_container:
        name: redmine
        image: redmine:latest
        published_ports:
          - 3000:3000
        restart_policy: always
        restart: yes
        pull: yes
        env_file: .env

- name: Install datadog
  hosts: webservers
  tags: monitoring

  tasks:
    - name: Setup datadog
      include_role:
        name: datadog.datadog


