db_host: "{{ vault_db_host }}"
db_port: "{{ vault_db_port }}"
db_username: "{{ vault_db_username }}"
db_password: "{{ vault_db_password }}"

db_name: redmine
datadog_api_key: "{{ vault_datadog_api_key }}"

datadog_site: "datadoghq.com"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Application health check status
        url: "http://localhost:3000"
        timeout: 5
        method: GET
